version: '2'

volumes:
  vastgoedfiles:

services:
  funda-scraper:
    restart: always
    build: .
    ports:
      - "8080:80"
    volumes:
      - vastgoedfiles:/home/meteorapp/build/bundle/programs/web.browser/app/data
